---
title: "Dis manibus in space and time"
author: "Petra Hermankova"
date: "24/08/2021"
output:
  html_document:
    theme: united
    toc: yes
    toc_float: true
    number_sections: true
    toc_depth: 2
    df_print: paged
---

```{r}
#install.packages("reticulate")
library(tidyverse)
library(reticulate)
library(jsonlite)
use_python("/usr/local/bin/python") # use this if you have local python installed
```

```{python}
# pip install seems not working
#pip install seaborn
#py_install("seaborn")
import geopandas as gpd # https://vincent.doba.fr/posts/20210407_install-fiona-on-windows/ & https://geopandas.org/getting_started/install.html Issues with geopandas on windows
import requests
import seaborn as sns
import matplotlib.colors as mcolors
import matplotlib.pyplot as plt
from scipy.stats import trapz
import scipy
#import nltk
import json
import tempun
#import sddk
import numpy as np
import pandas as pd
pd.options.display.max_columns = 1000  # to see all columns
```


```{r}
EDH_DM$not_before <- as.numeric(as.character(EDH_DM$not_before))
EDH_DM$not_after <- as.numeric(as.character(EDH_DM$not_after))
```

```{python}

# How many inscriptions have both dates?
EDH_dated = r.EDH_DM[(r.EDH_DM["not_before"].notnull()) | (r.EDH_DM["not_after"].notnull())]
len(EDH_dated)
```

```{python}
# Generate a list of 1000 random dates for each inscription in the dataset
EDH_dated["random_dates"] = EDH_dated.apply(lambda row: tempun.model_date(
    row["not_before"], row["not_after"], size=1000,), axis=1)
```

```{r}
# saving as r-object
py$EDH_dated -> EDH_dated
```

```{python}
# Count random dates in temporal timeblocks in a specified time range (from 200 BC to 600 AD, temporal blocks by 25 years)
EDH_complete_simulations = tempun.timeblocks_from_randoms(
    EDH_dated, "random_dates", [-200, 600, 25])
```


```{python}
# Figure 1
# plot all the dataset to see the epigraphic production in time
plt.style.use("seaborn-white")
plt.rcParams['figure.dpi'] = 300
plt.rcParams['font.size'] = 10
tab_colors_list = list(mcolors.TABLEAU_COLORS.keys())
fig, ax = plt.subplots(figsize=(14, 6), tight_layout=True)
tempun.plot_timeblocks_data(
    EDH_complete_simulations, ax=ax, color="blue", label=f"EDH (n={len(EDH_dated)})")
    
ax.set_xlabel("Year", weight="bold")
ax.set_ylabel("Count", weight="bold")
ax.set_title("Total epigraphic production over time (EDH)")
ax.legend(title="Data source", title_fontsize="large", bbox_to_anchor=(1, 1), loc='upper right')
#plt.axvline(x=212, linewidth=0.5, color = 'orange', linestyle='dashed')
#fig.suptitle(f'Comparison of epigraphic production over time', fontsize=16,fontweight="bold")
plt.savefig('../figures/Fig1_Epi_production_time.png')
fig
```


```{python}
# Inscriptions by their type over time, EDH
simulations_by_type_len_EDH = []
for ins_type in r.EDH_DM["form_dis_manibus"].unique():
    if ins_type != "NULL":
        subset_df = EDH_dated[EDH_dated["form_dis_manibus"] == ins_type]
        simulations_by_type_len_EDH.append((ins_type, len(subset_df)))
simulations_by_type_len_EDH = sorted(
    simulations_by_type_len_EDH, key=lambda x: x[1], reverse=True)
simulations_by_type_len_EDH
simulations_by_type_EDH = []
for ins_type_tup in simulations_by_type_len_EDH[:8]:
    subset_df = EDH_dated[EDH_dated["form_dis_manibus"]
                          == ins_type_tup[0]]
    simulations = tempun.timeblocks_from_randoms(
        subset_df, "random_dates", [-200, 600, 25])
    ins_type_N = len(subset_df)
    simulations_by_type_EDH.append([ins_type_tup[0], ins_type_N, simulations])
simulations_by_type_EDH = sorted(
    simulations_by_type_EDH, key=lambda x: x[1], reverse=True)
date_vars_by_instypes = []
for ins_type_tup in simulations_by_type_len_EDH[:10]:
    subset_df = EDH_dated[EDH_dated["form_dis_manibus"]
                          == ins_type_tup[0]]
    date_vars = []
    for n in range(100):
        date_vars.append(
            [date_var[n] for date_var in subset_df["random_dates"] if date_var != None])
    date_vars_by_instypes.append(date_vars)
```

```{python}
simulations_by_type_len_EDH
```

```{python}
# Figure 2
plt.style.use("seaborn-white")
plt.rcParams['figure.dpi'] = 300
plt.rcParams['font.size'] = 10
fig, [ax1, ax2] = plt.subplots(2, 1, figsize=(14, 12), tight_layout=True)
for ins_type_sims, color in zip(simulations_by_type_EDH, tab_colors_list[:len(simulations_by_type_EDH)]):
    tempun.plot_timeblocks_data(ins_type_sims[2], ax=ax1, color=color)
ax1.set_xlabel("Year", weight="bold")
ax1.set_ylabel("Count", weight="bold")
ax1.set_title(f"`Dis manibus` formula on inscriptions over time (EDH, n={len(EDH_dated)})", weight="bold")
markers = [plt.Line2D([0, 0], [0, 0], color=color, lw=4)
           for color in tab_colors_list[:len(simulations_by_type_EDH)]]
legend_labels_EDH = [tup[0] + " (n={})".format(str(tup[1])) for tup in simulations_by_type_EDH]
ax1.legend(markers, legend_labels_EDH, numpoints=1,  
           title=f"Formula types (EDH n={len(EDH_dated)})", title_fontsize="large", bbox_to_anchor=(1, 1), loc='upper right')
plt.savefig('../figures/Fig2_Typologies_comparison_time.png')
fig
```



## Periods 
```{python}
# periods definitions
periods = {  # to avoid overlaps, startdates are postponed by one year, when needed
    "Late Roman Republic": {"startdate": -200, "enddate": -26, "duration": 175},
    "Julio-Claudian dyn.": {"startdate": -27, "enddate": 68, "duration": 95},
    "Flavian dyn.": {"startdate": 69, "enddate": 96,"duration": 28},
    "Nerva-Antonine dyn.": {"startdate": 97, "enddate": 192, "duration": 96},
    "Severan dyn.": {"startdate": 193, "enddate": 235, "duration": 43},
    "Military emperors": {"startdate": 236, "enddate": 284,"duration": 49},
    "Tetrarchy-Constantine I": {"startdate": 285, "enddate": 337,"duration": 53},
    "Late Roman Empire": {"startdate": 338, "enddate": 600,"duration": 263}
}
timeblocks_periods = [(periods[period]["startdate"],
                       periods[period]["enddate"],
                       periods[period]["duration"]) for period in periods]
timeblocks_periods
```

```{python}
def date_to_str(date):
    if date < 0:
        date = str(abs(date)) + " BC"
    else:
        date = "AD " + str(date)
    return date
periods_labels = []
for period in periods.keys():
    start = date_to_str(periods[period]["startdate"])
    end = date_to_str(periods[period]["enddate"])
    periods_labels.append(period + "\n({0}-{1})".format(start, end))
periods_labels
```

```{python}
# loading shapefile from Pleaides for the largest extent of the Roman Empire, AD 117
# source: https://raw.githubusercontent.com/pelagios/magis-pleiades-regions/main/pleiades-regions-magis-pelagios.geojson
pleiades_regions = gpd.read_file('../data/pleiades_regions.geojson', driver='GeoJSON')
RE_merged = pleiades_regions.unary_union
```

```{python}
def get_date_var(randoms):
    try:
        return randoms[0]
    except:
        return None
# selecting one random date out of the 1000 version
EDH_dated["date_var_1"] = EDH_dated["random_dates"].apply(get_date_var)
```


```{python}
# modifying coordinates in EDH to fit the script
EDH_dated[['Longitude', 'Latitude']] = pd.DataFrame(EDH_dated.coordinates. tolist(), index=EDH_dated.index)
```

```{python}
EDH_dated_df_by_periods = []
for period in timeblocks_periods:
    EDH_dated_sample = EDH_dated[EDH_dated["date_var_1"].between(
        period[0], period[1])]
    # tranforming EDH as geodataframe
    EDH_dated_sample = EDH_dated_sample[EDH_dated_sample["latitude"].notnull()]
    EDH_dated_sample = gpd.GeoDataFrame(EDH_dated_sample, geometry=gpd.points_from_xy(EDH_dated_sample["longitude"], EDH_dated_sample["latitude"]))
    # selecting only those dated and within borders of the Empire (the largest extent in AD 117)
    EDH_dated_sample = EDH_dated_sample[EDH_dated_sample.within(RE_merged)]
    EDH_dated_df_by_periods.append(EDH_dated_sample)
```

```{python}
# Figure 3
# plot EDH inscriptions with location in 8 plots grouped by period
plt.style.use("seaborn-white")
plt.rcParams['figure.dpi'] = 300
plt.rcParams['font.size'] = 10
fig, axs  = plt.subplots(4, 2, figsize=(7, 7), tight_layout=True)
contexts_pct = {}
    
for df_edh, ax, period in zip(EDH_dated_df_by_periods, axs.ravel(), periods_labels):
    pleiades_regions.plot(ax=ax, color="lightgray")
    df_edh.plot(markersize=0.04, color="darkblue", ax=ax, alpha=0.2, label=len(df_edh))
    ax.set_title(period, fontsize=6)
    ax.set_axis_off()
    markers = [plt.Line2D([0,0],[0,0],color=color, marker=".", linestyle="") for color in ["darkblue", "red"]]
    legend_labels = ["EDH (n={0})".format(str(len(df_edh)))]
    
    ax.legend(markers, legend_labels, numpoints=1, bbox_to_anchor=(0.6, 1), loc='upper left', fontsize=5)
   
plt.tight_layout(pad=0)
plt.subplots_adjust(wspace=0.0, hspace=0.0)
#fig.suptitle(f'Spatial extent of the epigraphic production by historic period', fontsize=8, fontweight="bold")
plt.savefig('../figures/Fig3_Formulae_production_periods.png')
fig
```
# Combined two most common types as time slices

```{python}
dis_manibus = EDH_dated[EDH_dated["form_dis_manibus"] == "dis manibus"]
len(dis_manibus)
```
```{python}
diis_manibus = EDH_dated[EDH_dated["form_dis_manibus"] == "diis manibus"]
len(diis_manibus)
```

```{python}
dis_manibus_sac = EDH_dated[EDH_dated["form_dis_manibus"] == "dis manibus sacrum"]
len(dis_manibus_sac)
```
```{python}
diis_manibus_sac = EDH_dated[EDH_dated["form_dis_manibus"] == "diis manibus sacrum"]
len(diis_manibus_sac)
```


```{python}
EDH_dated_df_by_periods_dm = []
for period in timeblocks_periods:
    EDH_dated_sample_dm = dis_manibus[dis_manibus["date_var_1"].between(
        period[0], period[1])]
    # tranforming EDH as geodataframe
    EDH_dated_sample_dm = EDH_dated_sample_dm[EDH_dated_sample_dm["latitude"].notnull()]
    EDH_dated_sample_dm = gpd.GeoDataFrame(EDH_dated_sample_dm, geometry=gpd.points_from_xy(EDH_dated_sample_dm["longitude"], EDH_dated_sample_dm["latitude"]))
    # selecting only those dated and within borders of the Empire (the largest extent in AD 117)
    EDH_dated_sample_dm = EDH_dated_sample_dm[EDH_dated_sample_dm.within(RE_merged)]
    EDH_dated_df_by_periods_dm.append(EDH_dated_sample_dm)
```

```{python}
EDH_dated_df_by_periods_dm
```


```{python}
EDH_dated_df_by_periods_dms = []
for period in timeblocks_periods:
    EDH_dated_sample_dms = dis_manibus_sac[dis_manibus_sac["date_var_1"].between(
        period[0], period[1])]
    # tranforming EDH as geodataframe
    EDH_dated_sample_dms = EDH_dated_sample_dms[EDH_dated_sample_dms["latitude"].notnull()]
    EDH_dated_sample_dms = gpd.GeoDataFrame(EDH_dated_sample_dms, geometry=gpd.points_from_xy(EDH_dated_sample_dms["longitude"], EDH_dated_sample_dms["latitude"]))
    # selecting only those dated and within borders of the Empire (the largest extent in AD 117)
    EDH_dated_sample_dms = EDH_dated_sample_dms[EDH_dated_sample_dms.within(RE_merged)]
    EDH_dated_df_by_periods_dms.append(EDH_dated_sample_dms)
```

```{python}
EDH_dated_df_by_periods_dms
```


```{python}
# Figure 4
# plot EDH inscriptions with location in 8 plots grouped by period
plt.style.use("seaborn-white")
plt.rcParams['figure.dpi'] = 300
plt.rcParams['font.size'] = 10
fig, axs  = plt.subplots(4, 2, figsize=(7, 7), tight_layout=True)
contexts_pct = {}
    
for df_edh_dms, df_edh_dm, ax, period in zip(EDH_dated_df_by_periods_dms, EDH_dated_df_by_periods_dm, axs.ravel(), periods_labels):
    pleiades_regions.plot(ax=ax, color="lightgray")
    df_edh_dm.plot(markersize=0.04, color="darkblue", ax=ax, alpha=0.3, label=len(df_edh_dms))
    df_edh_dms.plot(markersize=0.04, color="red", ax=ax, alpha=0.3, label=len(df_edh_dm))
    ax.set_title(period, fontsize=6)
    ax.set_axis_off()
    markers = [plt.Line2D([0,0],[0,0],color=color, marker=".", linestyle="") for color in ["darkblue", "red"]]
    legend_labels = ["dis manibus (n={0})".format(str(len(df_edh_dm))), 
                     "dis manibus sacrum (n={0})".format(str(len(df_edh_dms)))]
    
    ax.legend(markers, legend_labels, numpoints=1, bbox_to_anchor=(0.6, 1), loc='upper left', fontsize=5)
   
plt.tight_layout(pad=0)
plt.subplots_adjust(wspace=0.0, hspace=0.0)
fig.suptitle(f'Spatial distribution of "dis manibus" formula by historic period (EDH dataset)', fontsize=8, fontweight="bold")
plt.savefig('../figures/Fig4_Formulae_compared_production_periods.png')
fig
```



# Creating three snaphots in time

From simulated dates take 1-100, 101-200, 201-300 and then create a network.

```{r}
EDH_dated[1:4]
```

